name: recipe CI
on:
  - push
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Run Verify
        run: ./mvnw verify

      - name: Run  tests
        run: ./mvnw test

